### ISSUE TITLE
Designer window doesn't works in Samples

### ISSUE THREAD

**Issue by andrewryan-andie** [DavidRogersDev/WinformsMVP#5]
I just downloaded and I got this exception in Designer window:

```
The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  MainView --- The base class 'WinFormsMvp.Forms.MvpForm' could not be loaded.  Ensure the assembly has been referenced and that all projects have been built. | The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  MainView --- The base class 'WinFormsMvp.Forms.MvpForm' could not be loaded.  Ensure the assembly has been referenced and that all projects have been built.
```

Call Stack:
```
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.EnsureDocument(IDesignerSerializationManager manager)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host)
```

**Comment by andrewryan-andie** [comment]
ok, i got it fixed

LoadChildForm replaced with this:

 public void LoadChildForm(Type childFormType)
        {
            var constructors = childFormType.GetConstructors();

            if (constructors[0].Invoke(new object[] { }) is Form destinationView)
                destinationView.ShowDialog();
        }
